# Generated by Django 4.0.4 on 2022-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_filter',
            name='price',
            field=models.CharField(choices=[('100 - 1000', -900), ('1000 - 5000', '1000 - 5000'), ('5000 - 10000', '5000 - 10000'), ('10000 - 20000', '10000 - 20000'), ('20000 - 50000', '20000 - 50000')], max_length=13),
        ),
    ]
