# Generated by Django 4.0.4 on 2022-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_price_filter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='price_filter',
            name='price',
            field=models.CharField(choices=[('100 - 1000', '100.00 - 1000'), ('1000 - 5000', '1000 - 5000'), ('5000 - 10000', '5000 - 10000'), ('10000 - 20000', '10000 - 20000'), ('20000 - 50000', '20000 - 50000')], max_length=13),
        ),
    ]
