# Generated by Django 4.0.4 on 2022-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_image_alter_price_filter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
            ],
        ),
    ]
